### ISSUE TITLE
New entry form placed incorrectly when the_content action run more than once

### ISSUE THREAD

**Issue by PavelK27** [Automattic/liveblog#325]
**Steps to reproduce:**
1. Add liveblog to a page with several the_content filters running on it, i.e. when some parts of the content being added through the page load process
2. Entry form will be displayed only on the first run of the action and placed incorrectly in some cases.

PR: https://github.com/Automattic/liveblog/pull/324

**Comment by philipjohn** [comment]
Could you provide examples of what additional filters on `the_content` end up producing this issue?

> Entry form will be displayed only on the first run of the action

This _sounds_ correct to me, because we only want the Liveblog inserted once. If the filter is running multiple times, it might be that a theme or plugin is re-running `apply_filters( 'the_content', $content );` causing Liveblog to try adding the Liveblog for a second time.

**Comment by GaryJones** [comment]
Closing for lack of feedback.
