### ISSUE TITLE
Word-break: break-all gives awkward, undesirable word breaks

### ISSUE THREAD

**Issue by kevinlisota** [Automattic/liveblog#440]
In a recent change to the liveblog CSS, the following property was introduced: `word-break: break-all`

This leads to very awkward and unreadable line breaks like this.

![image](https://user-images.githubusercontent.com/4521682/39791703-fa07881a-52f1-11e8-948b-7167145387dc.png)

Is there a reason this was introduced? I suggest removing it.

**Comment by philipjohn** [comment]
@jasonagnew Are you able to provide any insight on this one please?

**Comment by combs** [comment]
Honestly this looks like something that would have happened if the plugin was tested with short dummy content, like asdf, instead of pesky real world users like us. Our poor editors were (futilely) trying to add manual <br/> to their writeups to dodge hundreds of terrible mid-word breaks. Anything longer than a sentence is affected by this. I'd love to see a fix. I can submit a pull request if necessary.

**Comment by paulschreiber** [comment]
We had to fix this, too. It should definitely be removed from core.

**Comment by philipjohn** [comment]
Fixed in #460
