### ISSUE TITLE
Fix PHPCS sniffs on PRs

### ISSUE THREAD

**Issue by philipjohn** [Automattic/liveblog#540]
> The command "if [[ "$SNIFF" == "1" ]]; then $PHPCS_DIR/scripts/phpcs -p -s -v -n . --standard="WordPress-VIP" --extensions=php; fi" exited with 0.

It looks like PHPCS isn't running as expected via Travis on Pull Requests. Rather than failing, the Travis tests are passing, masking the fact that there's even an issue.

We need to:

- [ ] Ensure PHPCS runs reliably via Travis
- [ ] Include the WordPress Coding Standards
- [ ] Include the `WordPress-VIP-Go` ruleset from [VIP Coding Standards](https://github.com/Automattic/VIP-Coding-Standards)

**Comment by GaryJones** [comment]
I'd like to see this repo support PHPCS checks locally - that is, PHPCS/WPCS/VIPCS/PHPCompatibilityWP all required as development dependencies in Composer, and then a `.phpcs.xml.dist` config file to handle that all.

Once that's done, then all that's needed in Travis (when running sniff checks), is a `composer install`, rather than individual git clones.
