### ISSUE TITLE
Liveblog 1.9.3 conflict with Social Warfare social media plugin

### ISSUE THREAD

**Issue by kenaiandrews** [Automattic/liveblog#604]
The Live Blog plug in 1.9.3 does not seem to play nice with the Social Warfare plugin. Initially, I thought it was the Social Warfare plug in, but they have determined it is in fact the live blog plugin which is conflicting with Social Warfare plugin. I deactivated Live Blog, and activated Social Warfare and noted my website at www.mmacrossfire.com is fine. Re-activating Live Blog with Social Warfare brought down my website and produced the following error message: 

Fatal error: Uncaught Error: Call to a member function get() on null in /home/mmacross/public_html/wp-includes/query.php:30 Stack trace: #0 /home/mmacross/public_html/wp-content/plugins/liveblog/liveblog.php(554): get_query_var('liveblog') #1 /home/mmacross/public_html/wp-content/plugins/liveblog/liveblog.php(103): WPCOM_Liveblog::is_entries_ajax_request() #2 /home/mmacross/public_html/wp-includes/class-wp-hook.php(286): WPCOM_Liveblog::add_custom_post_type_support(Object(WP_Query)) #3 /home/mmacross/public_html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array) #4 /home/mmacross/public_html/wp-includes/plugin.php(515): WP_Hook->do_action(Array) #5 /home/mmacross/public_html/wp-includes/class-wp-query.php(1634): do_action_ref_array('pre_get_posts', Array) #6 /home/mmacross/public_html/wp-includes/class-wp-query.php(3230): WP_Query->get_posts() #7 /home/mmacross/public_html/wp-includes/post.php(1763): WP_Query->query(Array) #8 /home/mmacross/public_html/wp-content/plugins/1social-warfare1/lib/utilities in /home/mmacross/public_html/wp-includes/query.php on line 30

Thoughts?

Regards,

Kenai

**Comment by vishnusingamsetty** [comment]
We are also facing the same issue in our blog https://blog.humanesociety.org

**Comment by philipjohn** [comment]
The error happens when Liveblog uses the WP function `[get_query_var()](https://developer.wordpress.org/reference/functions/get_query_var/)'. This function simple calls `$wp_query->get()` which _should_ be available as it's a pretty critical part of WordPress functionality. That suggests that somewhere the Social Warfare plugin is changing or making `$wp_query` unavailable somehow. Otherwise the `get()` call would work fine.

I'd suggest that's something that needs fixing in the Social Warfare plugin.

**Comment by dev-triboo** [comment]
Same issue here, in two different sites with two different sets of plugins and theme. 

I cannot trace the cause to other plugin so I fixed with this https://gist.github.com/joshbetz/13d631aa3ee229d0d626 (and I have to do every time I deploy the webiste).

@philipjohn I think dev team should take a look to this issue because it pop-ups often
