### ISSUE TITLE
Author list not cached sufficiently

### ISSUE THREAD

**Issue by paulschreiber** [Automattic/liveblog#606]
See #417 #568.

The "fix" reduces the time between fetches. Only one fetch is needed per page load. No need to re-fetch the author list.

**Comment by philipjohn** [comment]
This code does an author search, rather than fetching a list of users. While we could cache the search results for each query that's probably going to be excessive because the likelihood of those terms being searched again could be pretty low, and only performed by a limited set of users.

Willing to be convinced otherwise if there is a demonstrably negative performance impact to not caching the searches.
