### ISSUE TITLE
Provide RSS feed of Liveblog

### ISSUE THREAD

**Issue by nitinthewiz** [Automattic/liveblog#96]
It would be an excellent idea to provide an RSS feed of the liveblog, allowing users to post to various social networks using such a feed.

The following would be required - 
1. A format that allows the feed to have the text of each liveblog post as a title
2. Allow any attached images to be a part of the feed.

**Comment by philipjohn** [comment]
Do you foresee any other uses beyond posting to social networks?

I'm asking because I'm wondering whether a feed is the best choice. With a feed we might have issues when liveblog entries are edited or deleted as the entry will have already gone out in the feed. For edits, re-publishing that entry on the feed could be confusing, and deleted entries are of course not deleted from their destinations without some sort of tigher integration than RSS allows.

What might be better is for explicit social integrations (as proposed in #186). This could give the editor the ability to send entries to social networks, possibly selectively, and with a way attach the social network update so that it can be updated/removed along with the original liveblog.
